const express = require('express');
const cors = require('cors');
const cookieParser = require('cookie-parser');
require('dotenv').config();
const logger = require('./utils/logger');

const app = express();
const PORT = process.env.PORT || 4000;

const { poolPromise } = require('./config/db');
const jwt = require('jsonwebtoken');

let maintenanceCache = {
    advertencia: false,
    bloqueo: false,
    limite: '',
    lastFetched: 0
};

global.getMaintenanceStatus = async function() {
    const now = Date.now();
    if (now - maintenanceCache.lastFetched < 30000) {
        return maintenanceCache;
    }

    try {
        const pool = await poolPromise;
        const res = await pool.request().query("SELECT clave, valor FROM Configuracion");
        
        let advertencia = false;
        let bloqueo = false;
        let limite = '';
        
        res.recordset.forEach(row => {
            if (row.clave === 'advertencia_mantenimiento') {
                advertencia = row.valor === 'true';
            }
            if (row.clave === 'bloqueo_mantenimiento') {
                bloqueo = row.valor === 'true';
            }
            if (row.clave === 'mantenimiento_limite') {
                limite = row.valor;
            }
        });

        maintenanceCache = {
            advertencia,
            bloqueo,
            limite,
            lastFetched: now
        };
    } catch (err) {
        console.error("❌ Error al refrescar caché de mantenimiento:", err.message);
    }
    return maintenanceCache;
};

global.invalidateMaintenanceCache = function() {
    maintenanceCache.lastFetched = 0;
};

async function inicializarMantenimiento() {
    try {
        const pool = await poolPromise;
        
        // Crear tabla Inventario si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Inventario (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                codigo VARCHAR(100) NOT NULL,
                empresa VARCHAR(50) NOT NULL,
                detalle TEXT,
                marca VARCHAR(100),
                linea VARCHAR(100),
                sublinea VARCHAR(100),
                costo NUMERIC(18, 2),
                precio_final NUMERIC(18, 2),
                stock INT DEFAULT 0,
                disponible INT DEFAULT 0,
                fecha_actualizacion TIMESTAMP,
                empleado VARCHAR(100),
                CONSTRAINT UQ_Inventario_Codigo_Empresa UNIQUE (codigo, empresa)
            );
        `);
        logger.info("📦 Tabla Inventario verificada / creada con éxito");

        // Crear tabla Configuracion si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Configuracion (
                clave VARCHAR(50) PRIMARY KEY,
                valor VARCHAR(255) NOT NULL
            );
        `);
        
        // Asegurar que las claves iniciales de mantenimiento existen
        await pool.request().query(`
            INSERT INTO Configuracion (clave, valor) VALUES ('advertencia_mantenimiento', 'false') ON CONFLICT (clave) DO NOTHING;
            INSERT INTO Configuracion (clave, valor) VALUES ('bloqueo_mantenimiento', 'false') ON CONFLICT (clave) DO NOTHING;
            INSERT INTO Configuracion (clave, valor) VALUES ('mantenimiento_limite', '') ON CONFLICT (clave) DO NOTHING;
        `);

        // Crear tabla MapeoProductosIA si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS MapeoProductosIA (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                detalle_original VARCHAR(800) NOT NULL,
                codigo_inventario VARCHAR(100) NOT NULL,
                empresa VARCHAR(50) NOT NULL,
                fecha_mapeo TIMESTAMP DEFAULT NOW(),
                CONSTRAINT UQ_Mapeo_Detalle_Empresa UNIQUE (detalle_original, empresa)
            );
        `);
        logger.info("🧠 Tabla MapeoProductosIA verificada / creada con éxito");

        // Crear tabla Usuarios si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Usuarios (
                id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR(255),
                email VARCHAR(255) UNIQUE NOT NULL,
                password_hash VARCHAR(255),
                rol VARCHAR(50) DEFAULT 'usuario',
                empresa VARCHAR(100),
                estado BOOLEAN DEFAULT FALSE,
                habilitado BOOLEAN DEFAULT TRUE,
                empresa_acceso VARCHAR(255),
                puede_importar BOOLEAN DEFAULT FALSE,
                codigo_verificacion VARCHAR(50),
                codigo_expira TIMESTAMP,
                ultimo_acceso TIMESTAMP,
                foto_perfil VARCHAR(255),
                fecha_creacion TIMESTAMP DEFAULT NOW()
            );
        `);
        logger.info("👤 Tabla Usuarios verificada / creada con éxito");

        // Crear tabla Destinatarios si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Destinatarios (
                id_destinatario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre_hospital VARCHAR(255) UNIQUE NOT NULL,
                tipo_segmento VARCHAR(100),
                segmento_provincia VARCHAR(100),
                cuit VARCHAR(50),
                condicion_iva VARCHAR(100),
                telefono VARCHAR(100),
                email VARCHAR(255),
                direccion TEXT,
                localidad VARCHAR(100),
                provincia VARCHAR(100),
                notas TEXT,
                fecha_creacion TIMESTAMP DEFAULT NOW()
            );
        `);
        logger.info("🏢 Tabla Destinatarios verificada / creada con éxito");

        // Crear tabla Productos si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Productos (
                id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre_detalle VARCHAR(800) UNIQUE NOT NULL
            );
        `);
        logger.info("📦 Tabla Productos verificada / creada con éxito");

        // Crear tabla Procesos si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Procesos (
                id_proceso_db INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nro_proceso VARCHAR(255),
                fecha_apertura TIMESTAMP,
                id_destinatario INTEGER REFERENCES Destinatarios(id_destinatario) ON DELETE CASCADE,
                id_usuario_creador INTEGER REFERENCES Usuarios(id_usuario),
                fecha_importacion TIMESTAMP DEFAULT NOW(),
                CONSTRAINT UQ_Proceso_Destinatario UNIQUE (nro_proceso, id_destinatario)
            );
        `);
        logger.info("⚙️ Tabla Procesos verificada / creada con éxito");

        // Crear tabla Renglones si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Renglones (
                id_renglon INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_proceso_db INTEGER REFERENCES Procesos(id_proceso_db) ON DELETE CASCADE,
                id_destinatario INTEGER REFERENCES Destinatarios(id_destinatario),
                id_producto INTEGER REFERENCES Productos(id_producto),
                nro_renglon_item VARCHAR(50),
                cantidad NUMERIC(18,2) DEFAULT 0,
                precio_ganador NUMERIC(18,2) DEFAULT 0,
                primer_oferente VARCHAR(255),
                marca_ganadora VARCHAR(255),
                segundo_pu NUMERIC(18,2) DEFAULT 0,
                segundo_oferente VARCHAR(255),
                marca_segundo VARCHAR(255),
                mi_pu NUMERIC(18,2) DEFAULT 0,
                mi_marca VARCHAR(255),
                ganamos INTEGER DEFAULT 0
            );
        `);
        logger.info("📝 Tabla Renglones verificada / creada con éxito");

        // Crear tabla ContactosHospitales si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS ContactosHospitales (
                id_contacto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_destinatario INTEGER REFERENCES Destinatarios(id_destinatario) ON DELETE CASCADE,
                nombre_contacto VARCHAR(255),
                rol_puesto VARCHAR(100),
                telefono VARCHAR(100),
                email VARCHAR(255),
                empresa VARCHAR(50) DEFAULT 'TODAS',
                notas TEXT,
                fecha_creacion TIMESTAMP DEFAULT NOW()
            );
        `);
        logger.info("📞 Tabla ContactosHospitales verificada / creada con éxito");

        // Crear tabla ProductosPM si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS ProductosPM (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                detalle       TEXT NOT NULL,
                marca         VARCHAR(200) NOT NULL,
                pm            VARCHAR(100) NOT NULL,
                observaciones TEXT,
                fecha_carga   TIMESTAMP DEFAULT NOW(),
                CONSTRAINT UQ_PM_Detalle_Marca UNIQUE (detalle, marca)
            );
        `);
        logger.info("💊 Tabla ProductosPM verificada / creada con éxito");

        // Crear tabla Notificaciones si no existe
        await pool.request().query(`
            CREATE TABLE IF NOT EXISTS Notificaciones (
                id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa VARCHAR(50) NOT NULL,
                titulo VARCHAR(255) NOT NULL,
                mensaje TEXT NOT NULL,
                leido BOOLEAN DEFAULT FALSE,
                fecha_creacion TIMESTAMP DEFAULT NOW()
            );
        `);
        logger.info("🔔 Tabla Notificaciones verificada / creada con éxito");

        // Cargar valores iniciales en caché
        await global.getMaintenanceStatus();
        logger.info("🔧 Base de datos y caché de mantenimiento inicializadas.");
    } catch (err) {
        logger.error("❌ Error al inicializar base de datos en startup: " + err.message);
    }
}
inicializarMantenimiento();

const helmet = require('helmet');

// ==========================
// Middlewares
// ==========================
app.use(helmet({
    crossOriginResourcePolicy: false // Permite cargar recursos locales sin bloqueos estrictos de CORS
}));

app.use(cookieParser());

const allowedOrigins = [
    'http://localhost:5173',
    'http://localhost:3000',
    process.env.FRONTEND_URL
].filter(Boolean);

app.use(cors({
    origin: (origin, callback) => {
        // En desarrollo o si es el mismo origen, permitir. En producción, validar contra la whitelist.
        if (!origin || allowedOrigins.includes(origin) || process.env.NODE_ENV !== 'production') {
            callback(null, true);
        } else {
            callback(new Error('Acceso denegado por políticas de seguridad CORS'));
        }
    },
    credentials: true
}));

// Endpoint de salud del sistema (/api/health) libre de autenticación y mantenimiento
app.get('/api/health', async (req, res) => {
    try {
        const pool = await poolPromise;
        await pool.query('SELECT 1');
        res.json({
            status: 'ok',
            timestamp: new Date().toISOString(),
            db: 'connected',
            uptime: process.uptime()
        });
    } catch (err) {
        logger.error('Error en /api/health al conectar a BD: ' + err.message);
        res.status(503).json({
            status: 'error',
            db: 'disconnected'
        });
    }
});

// Ampliamos el límite a 10mb por los JSON de los Excel pesados
app.use(express.json({ limit: '10mb' })); 
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// ==========================
// Middleware de Mantenimiento Global
// ==========================
app.use(async (req, res, next) => {
    const estado = await global.getMaintenanceStatus();

    // Verificar si el límite de aviso previo por mantenimiento ya expiró
    if (estado.advertencia && estado.limite) {
        if (new Date() >= new Date(estado.limite)) {
            estado.bloqueo = true;
            estado.advertencia = false;
            estado.limite = '';
            
            // Sincronizar con la base de datos de manera asíncrona
            poolPromise.then(pool => {
                return pool.request().query(`
                    UPDATE Configuracion SET valor = 'true' WHERE clave = 'bloqueo_mantenimiento';
                    UPDATE Configuracion SET valor = 'false' WHERE clave = 'advertencia_mantenimiento';
                    UPDATE Configuracion SET valor = '' WHERE clave = 'mantenimiento_limite';
                `);
            }).then(() => {
                logger.info("⚡ [Mantenimiento] El tiempo límite expiró. El bloqueo general ha sido activado automáticamente.");
                global.invalidateMaintenanceCache();
            }).catch(dbErr => {
                logger.error("❌ Error al guardar bloqueo automático en base de datos: " + dbErr.message);
            });
        }
    }

    if (estado.bloqueo || process.env.MAINTENANCE_MODE === 'true') {
        if (req.path.startsWith('/api/auth/')) {
            return next();
        }

        const authHeader = req.headers.authorization;
        if (authHeader && authHeader.startsWith('Bearer ')) {
            const token = authHeader.split(' ')[1];
            try {
                const decoded = jwt.verify(token, process.env.JWT_SECRET);
                if (decoded.rol === 'admin') {
                    return next();
                }
            } catch (err) {
                // Token inválido o expirado
            }
        }

        return res.status(503).json({
            status: 'maintenance',
            message: 'El sistema se encuentra temporalmente fuera de servicio por tareas de mantenimiento y actualización.'
        });
    }
    next();
});

// ==========================
// Importar Rutas
// ==========================
const comparativasRoutes = require('./routes/comparativas.routes');
const authRoutes = require('./routes/auth.routes');
const statsRoutes = require('./routes/stats.routes');
const iaRoutes = require('./routes/ia.routes'); 
const importarRoutes = require('./routes/importar.routes');
const importarPdfRoutes = require('./routes/importarPdf.routes');
const seguimientoRoutes = require('./routes/seguimiento.routes');
const adminRoutes = require('./routes/admin.routes');
const adminLicitacionesRoutes = require('./routes/adminLicitaciones.routes');
const inventarioRoutes = require('./routes/inventario.routes');
const cotizadorRoutes = require('./routes/cotizador.routes');
const contactosRoutes = require('./routes/contactos.routes');
const notificacionesRoutes = require('./routes/notificaciones.routes');
const anmatRoutes = require('./routes/anmat.routes');

// ==========================
// Usar Rutas
// ==========================
app.use('/api/comparativas', comparativasRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/stats', statsRoutes);
app.use('/api/ia', iaRoutes);
app.use('/api/importar/pdf', importarPdfRoutes);
app.use('/api/importar', importarRoutes);
app.use('/api/seguimiento', seguimientoRoutes);
app.use('/api/admin/licitaciones', adminLicitacionesRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/inventario', inventarioRoutes);
app.use('/api/cotizador', cotizadorRoutes);
app.use('/api/contactos', contactosRoutes);
app.use('/api/notificaciones', notificacionesRoutes);
app.use('/api/anmat', anmatRoutes);

// Ruta base
app.get('/', (req, res) => {
    res.send('API de Droguería funcionando con estructura profesional');
});

// ==========================
// Manejo de Errores Global (Opcional pero recomendado)
// ==========================
app.use((err, req, res, next) => {
    logger.error('❌ Error no controlado: ' + err.stack);
    res.status(500).json({ 
        message: 'Ocurrió un error en el servidor',
        error: process.env.NODE_ENV === 'development' ? err.message : {} 
    });
});

app.listen(PORT, () => {
    logger.info(`🚀 Servidor corriendo en http://localhost:${PORT}`);
    logger.info(`📧 Mailer configurado para: ${process.env.EMAIL_USER}`);
});